# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='values',
            new_name='vs',
        ),
    ]
