# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='vs',
        ),
    ]
