# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_vs'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='short',
            field=models.CharField(default='', max_length=512),
        ),
    ]
