# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
