version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:

  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=psppi

  client:
      build:
        context: .
        dockerfile: ./compose/client/Dockerfile
      links:
        - django
      volumes:
        - .:/app
      command: npm start
      ports:
        - "3000:3000"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=psppi
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres





