# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0001_initial'),
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='columns.Column'),
        ),
    ]
