# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 02:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demography',
            name='values',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
