# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 01:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('text', models.CharField(default='', max_length=512)),
                ('values', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='demographics',
            field=models.ManyToManyField(null=True, to='responses.Demography'),
        ),
    ]
