# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 12:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0003_remove_demography_vs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='demographics',
        ),
        migrations.AddField(
            model_name='response',
            name='demographics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
