# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_vs'),
        ('responses', '0006_demography_nice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDemographyByQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('demography', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='responses.Demography')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='availabledemographybyquestion',
            unique_together=set([('year', 'demography', 'question')]),
        ),
    ]
