# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responses', '0007_auto_20160923_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledemographybyquestion',
            name='demography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_year_permutations', to='responses.Demography'),
        ),
        migrations.AlterField(
            model_name='availabledemographybyquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demog_year_permutations', to='questions.Question'),
        ),
    ]
