# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-12 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='title',
            new_name='text',
        ),
    ]
